server:
  port: 28080

spring:
  application:
    name: base-auth
  thymeleaf:
    cache: false
  #出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
